config/routes.rb
Rails.application.routes.draw do
  get 'saml/init'

  get 'saml/consume'

  root 'static_pages#home'

  get 'static_pages/about'

  get 'static_pages/help'

  get 'signup' => 'users#new'
  get 'login' => 'sessions#new'
  post 'login' => 'sessions#create'
  delete 'logout' => 'sessions#destroy'
  resources :users
  get 'users/new' 

end

app/models/user.rb
class User < ActiveRecord::Base
	attr_accessor :remember_token

	# def remember
	# 	self.remember_token = Usesr.new_token
	# 	update_attribute(:remember_digest, User.digest(remember_token))
	# end

	before_save { self.email = email.downcase }
	validates :name, presence: true, length: { maximum: 50 } 
	VALID_EMAIL_REGEX = 	/\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
	validates :email, presence: true, length: { maximum: 255 },
					format: { with: VALID_EMAIL_REGEX },
					uniqueness: { case_sensitive: false }

	has_secure_password
	validates :password, presence: true, length: { minimum: 6}

	# Returns the hash digest of the given string
	def User.digest(string)
		cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST :
														BCrypt::Engine.cost 
		BCrypt::Password.create(string, cost: cost)
	end

	# Returns a random token
	def User.new_token
		SecureRandom.urlsafe_base64
	end

	# Remembers a user in the databae for use in persistent sessions.
	def remember
		self.remember_token = User.new_token
		update_attribute(:remember_digest, User.digest(remember_token))
	end

	# Returns true if given token matches the digest
	def authenticated?(remember_token)
		return false if remember_digest.nil?
		BCrypt::Password.new(remember_digest).is_password?(remember_token)
	end

	# Forgets a user
	def forget
		update_attribute(:remember_digest, nil)
	end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  include SessionsHelper
end

app/controllers/saml_controller.rb
class SamlController < ApplicationController
  def init
  end

  def consume
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
  	user = User.find_by(email: params[:session][:email].downcase)
  	if user && user.authenticate(params[:session][:password])
      log_in user 
      remember user 
      redirect_to user
      # line above autoconverted by Rails to user_url(user)
  	else
  		flash[:danger] = 'Invalid email / password combination'
  		render 'new'
  	end
  end

  def destroy
    log_out if logged_in?
    redirect_to root_url
  end

end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def about
  end

  def help
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

	def show
		@user = User.find(params[:id])
	end

	def new
		@user = User.new
	end

	def create
		@user = User.new(user_params)
		if @user.save
			log_in @user
			flash[:success] = "Welcome to the Demo1 app!"
			redirect_to @user
		else
			render 'new'
		end
	end

	def index
		@users = User.all
	end	


	private

	def user_params
		params.require(:user).permit(:name, :email, :password, :password_confirmation)
	end


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/saml_helper.rb
module SamlHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper

	def log_in(user)
		session[:user_id] = user.id
	end

# Remembers user in a persistent session
	def remember(user)
		user.remember
		cookies.permanent.signed[:user_id] = user.id 
		cookies.permanent[:remember_token] = user.remember_token
	end

	def current_user
		if (user_id = session[:user_id])
			@current_user ||= User.find_by(id: user_id)
		elsif (user_id = cookies.signed[:user_id])
			user = User.find_by(id: user_id)
			if user && user.authenticated?(cookies[:remember_token])
				log_in user
				@current_user = user
			end
		end
	end


	def logged_in?
		!current_user.nil?
	end

	# Forgets a persistent session
	def forget(user)
		user.forget
		cookies.delete(:user_id)
		cookies.delete(:remember_token)
	end


	def log_out
		forget(current_user)
		session.delete(:user_id)
		@current_user = nil
	end

end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_header.html.erb
<header class = "navbar navbar-fixed-top navbar-inverse">
	<div class = "container">
		<%= link_to "demo", root_path, id: "logo" %>
		<nav>
			<ul class = "nav navbar-nav navbar-right">
				<li><%= link_to "Home", root_path %></li>
				<li><%= link_to "Help", static_pages_help_path %></li>
				<li><%= link_to "About", static_pages_about_path %> </li>

				<% if logged_in? %>
					<li><%= link_to "Users", users_path %> </li>
					<li class = "dropdown">
						<a href = '#' class = "dropdown-toggle" data-toggle="dropdown">
						Account <b class = "caret"></b>
						</a>
						<ul class = "dropdown-menu">
							<li><%= link_to "Profile", current_user %></li>
							<li class = "divider"></li>
							<li><%= link_to "Log out", logout_path, method: "delete" %>
							</li>
						</ul>
					</li>
				<% else %>
					<li><%= link_to "Log in", login_path %> </li>
				<% end %>
			</ul>
		</nav>
	</div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Demo1</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
	<!-- <div class = "navbar navbar-inverse navbar-stat-top"> -->
		<%= render 'layouts/header' %>

		<div class= "container-fluid">
			<%= yield %>
		</div>
	<!-- </div> -->

</body>
</html>

app/views/saml/consume.html.erb
<h1>Saml#consume</h1>
<p>Find me in app/views/saml/consume.html.erb</p>

app/views/saml/init.html.erb
<h1>Saml#init</h1>
<p>Find me in app/views/saml/init.html.erb</p>

app/views/static_pages/about.html.erb
<h1>StaticPages#about</h1>
<p>Find me in app/views/static_pages/about.html.erb</p>
<h1>About page</h1>

app/views/static_pages/help.html.erb
<h1>Help</h1>
<p>Find me in app/views/static_pages/help.html.erb</p>
<h1>Help page</h1>

app/views/static_pages/home.html.erb
<% provide(:title, 'Log in') %>
<h1>Here we go... Log in</h1>

<div class = "row">
	<div class = "col-md-6 col-md-offset-3">
		<h1>Demo1 Home Page</h1>
		<%= form_for(:session, url: login_path) do |f| %>

			<%= f.label :email %>
			<%= f.email_field :email, class: 'form-control' %>

			<%= f.label :password %>
			<%= f.password_field :password, class: 'form-control' %>

			<%= f.submit "Log in", class: "btn btn-primary" %>
		<% end %>

		<p>New user? <%= link_to "Sign up now!", signup_path %></p>

	</div>
</div>

app/views/users/index.html.erb
<% provide(:title, 'Sign up') %>

<div class = "row">
	<div class = "col-md-6 col-md-offset-3">
	<h1>Current Users</h1>
		<%= @users.each do |user| %>
			<h4><%= user.name %>: </h4> <h5> <%= user.email %></h5>
		<% end %>
	</div>
</div>

app/views/users/new.html.erb
<% provide(:title, 'Sign up') %>
<h1>Sign Up</h1>

<div class = "row">
	<div class = "col-md-6 col-md-offset-3">
		<%= form_for(@user) do |f| %>
			<%= f.label :name %>
			<%= f.text_field :name %>

			<%= f.label :email %>
			<%= f.email_field :email %>

			<%= f.label :password %>
			<%= f.password_field :password %>

			<%= f.label :password_confirmation, "Confirmation" %>
			<%= f.password_field :password_confirmation %>

			<%= f.submit "Create my account", class: "btn btn-primary" %>
		<% end %>
	</div>
</div>

app/views/users/show.html.erb
<h1>
<%= @user.name %>'s Profile
</h1>
<h3>You can email <%= @user.name %> at <%= @user.email %> </h3>

<p>View all writers <%= link_to "Poets", users_path %>